---
- name: Setup restic backups
  hosts: all
  tags:
    - setup
    - backup
    - restic
  become: true
  tasks:
    - name: Add python3-paramiko dependency for ssh ansible module
      ansible.builtin.package:
        name: python3-paramiko
        state: present
    - name: Ensure user ssh dir exists and is writeable
      ansible.builtin.file:
        path: "/root/.ssh"
        state: directory
        owner: "restic"
        group: "restic"
        mode: "0750"
    - name: Copy ssh private key for storage box access
      ansible.builtin.copy:
        content: "{{ vault_restic_repository_location_ssh_private_key }}"
        dest: /root/.ssh/backup_key
        owner: restic
        group: restic
        mode: "0600"
    - name: Configure storage box host in the ssh configuration
      community.general.ssh_config:
        host: "{{ vault_restic_repository_location_host }}"
        identity_file: "/root/.ssh/backup_key"
        ssh_config_file: "/root/.ssh/config"
        identities_only: true
        port: "23"
        strict_host_key_checking: "accept-new"
        state: present
  roles:
    - role: restic
      restic_user: "root" # we need to run as root, so we can grab a sql dump from a podman container
      restic_repos:
        sftp:
          location: "sftp:{{ vault_restic_repository_location_user }}@{{ vault_restic_repository_location_host }}"
          encrypted_password: "{{ vault_restic_repository_encrypted_password }}"
      restic_backups:
        pretix-data:
          repo: sftp
          src: /var/lib/containers/storage/volumes/systemd-pretix-data
          scheduled: true
          schedule_oncalendar: "*-*-* 03:30:00"
          exclude:
            exclude_caches: true
          monitoring_call: "date --utc --iso-8601=s > /var/lib/restic/restic-pretix-data.stamp"
          # set keep-within to guard against an attacker overwriting all "good" snapshots in append only mode
          # see https://restic.readthedocs.io/en/stable/060_forget.html#security-considerations-in-append-only-mode for details
          keep_within: "1m"
          keep_weekly: 8
        pretix-database:
          repo: sftp
          stdin: true
          stdin_cmd: "podman exec -i systemd-pretix-postgres pg_dump -U pretix pretix"
          stdin_filename: pretix_psql_dump.sql
          scheduled: true
          schedule_oncalendar: "*-*-* 03:35:00"
          monitoring_call: "date --utc --iso-8601=s > /var/lib/restic/restic-pretix-database.stamp"
          # set keep-within to guard against an attacker overwriting all "good" snapshots in append only mode
          # see https://restic.readthedocs.io/en/stable/060_forget.html#security-considerations-in-append-only-mode for details
          keep_within: "1m"
          keep_weekly: 8
