---
- name: Setup gesundheit
  hosts: all
  tags:
    - setup
    - gesundheit
    - monitoring
  become: true
  roles:
    - role: gesundheit
      gesundheit_http_enabled: true
      gesundheit_http_listen_ip: 127.0.0.1
      gesundheit_modules:
        - filename: gotify
          config:
            Handler:
              Module: "gotify"
              Config:
                Url: "{{ vault_gesundheit_gotify.url }}"
                Token: "{{ vault_gesundheit_gotify.token }}"
              Filter:
                - Module: "result-change"
        # push gesundheit data through vpn to local network
        - filename: handle-remote-backupmaschine
          config:
            Handler:
              Module: "remote"
              Config:
                Address: "10.88.42.12:9999"
                # pubkey is 7n/uq3G/vFojytMenj1cjrfNZIFbjUFtSVPJOJjA+Ro=
                PrivateKey: "{{ vault_gesundheit_node_private_key }}"
                PublicKey: "sDK9d9BYmf+O1ZFiavOBWXbuhhzZZ0eVt5yTM6PeVEs=" # pubkey of backupmaschine
        - filename: input-remote
          config:
            Input:
              Module: "remote"
              Config:
                Listen: ":9999"
                # pubkey is 7n/uq3G/vFojytMenj1cjrfNZIFbjUFtSVPJOJjA+Ro=
                PrivateKey: "{{ vault_gesundheit_node_private_key }}"
                Peers:
                  - PublicKey: "vLL+QKR+RKtnbAe+A+YfYOP45hSR+JTqkdK3pl2R1Gk=" # mediamaschine
        - filename: check-mediamaschine-alive
          config:
            Check:
              Module: "node-alive"
              Description: "Check if mediamaschine is alive"
              Interval: "1m"
              Config:
                Node: "mediamaschine" # node name is hostname by default
                MaxAbsenceTime: "5m"

        - filename: check-disk-space-root
          config:
            Check:
              Module: "disk-space"
              Description: "Check free space on root partition"
              Interval: "30m"
              Config:
                MountPoint: "/"
                MinAvailable: "1G"
        - filename: check-heartbeat
          config:
            Check:
              Module: "heartbeat"
              Description: "Send heartbeat"
              Interval: "30s"
        - filename: check-memory
          config:
            Check:
              Module: "memory"
              Description: "Check available memory"
              Interval: "5m"
              Config:
                MinAvailable: "500M"
        - filename: check-reboot-required
          config:
            Check:
              Module: "file-presence"
              Description: "Check if reboot is required"
              Interval: "1h"
              Config:
                Path: "/run/reboot-required"
                Present: false
        - filename: check-restic-wg-portal-data-health
          config:
            Check:
              Module: "file-mtime"
              Description: "Check restic backup health of wg-portal data"
              Interval: "1h"
              Config:
                Path: "/var/lib/restic/restic-wg-portal-data.stamp"
                MaxAge: "26h"
