---
- name: Setup gesundheit
  hosts: all
  tags:
    - setup
    - gesundheit
    - monitoring
  become: true
  roles:
    - role: gesundheit
      gesundheit_http_enabled: true
      gesundheit_http_listen_ip: 127.0.0.1
      gesundheit_modules:
        - filename: gotify
          config:
            Handler:
              Module: "gotify"
              Config:
                Url: "{{ vault_gesundheit_gotify.url }}"
                Token: "{{ vault_gesundheit_gotify.token }}"
              Filter:
                - Module: "result-change"
        - filename: check-disk-space-root
          config:
            Check:
              Module: "disk-space"
              Description: "free space on root partition"
              Interval: "30m"
              Config:
                MountPoint: "/"
                MinAvailable: "4G"
        - filename: check-heartbeat
          config:
            Check:
              Module: "heartbeat"
              Description: "Send heartbeat"
              Interval: "30s"
        - filename: check-memory
          config:
            Check:
              Module: "memory"
              Description: "available memory"
              Interval: "5m"
              Config:
                MinAvailable: "500M"
        - filename: check-reboot-required
          config:
            Check:
              Module: "file-presence"
              Description: "reboot is required"
              Interval: "1h"
              Config:
                Path: "/run/reboot-required"
                Present: false
        - filename: check-restic-pretix-data-health
          config:
            Check:
              Module: "file-mtime"
              Description: "restic backup health of pretix data"
              Interval: "1h"
              Config:
                Path: "/var/lib/restic/restic-pretix-data.stamp"
                MaxAge: "26h"
        - filename: check-pretix-health
          config:
            Check:
              Module: "http-status"
              Description: "pretix health"
              Interval: "5m"
              Config:
                Method: "GET"
                Url: "https://{{ pretix_domain }}/healthcheck/"
                Status: 200
        - filename: check-pretix-ssl-cert
          config:
            Check:
              Module: "tls-cert"
              Description: "pretix ssl cert"
              Interval: "1h"
              Config:
                Host: "{{ pretix_domain }}"
                Port: 443
                MinTTL: "24h"
